--
-- PostgreSQL database dump
--

\restrict 2QTQ9hWSQJdw9kHbyxA5E5vxbsTBnWQUOAOZEHZRHisuvGId0hnEhbVccj12NTH

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assistant_statushistory; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.assistant_statushistory (
    id bigint NOT NULL,
    old_status character varying(20) NOT NULL,
    new_status character varying(20) NOT NULL,
    changed_at timestamp with time zone NOT NULL,
    task_id bigint NOT NULL
);


ALTER TABLE public.assistant_statushistory OWNER TO ivymalika;

--
-- Name: assistant_statushistory_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.assistant_statushistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assistant_statushistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assistant_task; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.assistant_task (
    id bigint NOT NULL,
    task_code character varying(10) NOT NULL,
    intent character varying(50) NOT NULL,
    entities jsonb NOT NULL,
    risk_score integer NOT NULL,
    risk_label character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    employee_assignment character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    customer_email character varying(100),
    customer_name character varying(100),
    customer_phone character varying(20)
);


ALTER TABLE public.assistant_task OWNER TO ivymalika;

--
-- Name: assistant_task_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.assistant_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assistant_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assistant_taskmessage; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.assistant_taskmessage (
    id bigint NOT NULL,
    whatsapp_message text,
    email_message text,
    sms_message text,
    created_at timestamp with time zone NOT NULL,
    task_id bigint NOT NULL
);


ALTER TABLE public.assistant_taskmessage OWNER TO ivymalika;

--
-- Name: assistant_taskmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.assistant_taskmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assistant_taskmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assistant_taskstep; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.assistant_taskstep (
    id bigint NOT NULL,
    step_number integer NOT NULL,
    description text NOT NULL,
    task_id bigint NOT NULL
);


ALTER TABLE public.assistant_taskstep OWNER TO ivymalika;

--
-- Name: assistant_taskstep_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.assistant_taskstep ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assistant_taskstep_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO ivymalika;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO ivymalika;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO ivymalika;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO ivymalika;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO ivymalika;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO ivymalika;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO ivymalika;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO ivymalika;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO ivymalika;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: ivymalika
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: ivymalika
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO ivymalika;

--
-- Data for Name: assistant_statushistory; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.assistant_statushistory (id, old_status, new_status, changed_at, task_id) FROM stdin;
\.


--
-- Data for Name: assistant_task; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.assistant_task (id, task_code, intent, entities, risk_score, risk_label, status, employee_assignment, created_at, updated_at, customer_email, customer_name, customer_phone) FROM stdin;
1	VNH-NKLP2C	send_money	{"amount": 25000, "urgency": "high", "currency": "KES", "location": "Nairobi", "recipient": "John Kamau"}	65	Medium	In Progress	Finance	2026-04-18 22:19:40.237924+03	2026-04-18 22:19:40.237951+03	\N	\N	\N
2	VNH-L03IOJ	verify_document	{"urgency": "medium", "location": "Karen, Nairobi", "document_type": "land title"}	85	High	Pending	Legal	2026-04-18 22:19:40.275299+03	2026-04-18 22:19:40.275326+03	\N	\N	\N
3	VNH-XW00HJ	hire_service	{"date": "this Friday", "urgency": "low", "location": "Westlands", "service_type": "cleaner"}	35	Low	Pending	Operations	2026-04-18 22:19:40.287479+03	2026-04-18 22:19:40.287498+03	\N	\N	\N
4	VNH-3WMWWV	airport_transfer	{"date": "Saturday 6am", "urgency": "medium", "location": "JKIA"}	40	Medium	Completed	Operations	2026-04-18 22:19:40.297426+03	2026-04-18 22:19:40.297456+03	\N	\N	\N
5	VNH-B3Z236	check_status	{"notes": "Previous medical bill task", "urgency": "low"}	30	Low	In Progress	Support	2026-04-18 22:19:40.308008+03	2026-04-18 22:19:40.308031+03	\N	\N	\N
6	VNH-LHNOP8	check_status	{"date": null, "notes": null, "amount": null, "urgency": null, "currency": null, "location": null, "recipient": null, "service_type": null, "document_type": null}	30	Low	Pending	Support	2026-04-18 22:32:41.464298+03	2026-04-18 22:32:41.464331+03	\N	\N	\N
7	VNH-6UYWPG	check_status	{"date": null, "notes": null, "amount": null, "urgency": null, "currency": null, "location": null, "recipient": null, "service_type": null, "document_type": null}	30	Low	Pending	Support	2026-04-18 22:34:39.943643+03	2026-04-18 22:34:39.943668+03	\N	\N	\N
8	VNH-ED63IF	check_status	{"date": null, "notes": null, "amount": null, "urgency": null, "currency": null, "location": null, "recipient": null, "service_type": null, "document_type": null}	30	Low	Pending	Support	2026-04-18 22:35:21.854078+03	2026-04-18 22:35:21.854106+03	\N	\N	\N
9	VNH-5YOUQ0	check_status	{"date": null, "notes": null, "amount": null, "urgency": null, "currency": null, "location": null, "recipient": null, "service_type": null, "document_type": null}	30	Low	Pending	Support	2026-04-18 22:41:35.943804+03	2026-04-18 22:41:35.943829+03	\N	\N	\N
10	VNH-XLYWCA	send_money	{"amount": 25000, "urgency": "high", "currency": "KES", "location": "Nairobi", "recipient": "John Kamau"}	65	Medium	In Progress	Finance	2026-04-18 23:12:16.981342+03	2026-04-18 23:12:16.981361+03	\N	\N	\N
11	VNH-4F8C15	verify_document	{"urgency": "medium", "location": "Karen, Nairobi", "document_type": "land title"}	85	High	Pending	Legal	2026-04-18 23:12:16.989998+03	2026-04-18 23:12:16.990015+03	\N	\N	\N
12	VNH-7NH3ZC	hire_service	{"date": "this Friday", "urgency": "low", "location": "Westlands", "service_type": "cleaner"}	35	Low	Pending	Operations	2026-04-18 23:12:16.995068+03	2026-04-18 23:12:16.995084+03	\N	\N	\N
13	VNH-OSAU1L	airport_transfer	{"date": "Saturday 6am", "urgency": "medium", "location": "JKIA"}	40	Medium	Completed	Operations	2026-04-18 23:12:17.000075+03	2026-04-18 23:12:17.000085+03	\N	\N	\N
14	VNH-KF8NH0	check_status	{"notes": "Previous medical bill task", "urgency": "low"}	30	Low	In Progress	Support	2026-04-18 23:12:17.005283+03	2026-04-18 23:12:17.005298+03	\N	\N	\N
\.


--
-- Data for Name: assistant_taskmessage; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.assistant_taskmessage (id, whatsapp_message, email_message, sms_message, created_at, task_id) FROM stdin;
1	Hello! We have initiated your urgent transfer of KES 25,000 to John Kamau. Next steps: verifying receipt.	Dear Valued Customer, Your task VNH-NKLP2C (Send Money) has been received. Risk level: Medium. We are currently processing the disbursement. Warm regards, Vunoh Global Team	Vunoh: Task VNH-NKLP2C started. KES 25k being sent to John Kamau.	2026-04-18 22:19:40.272069+03	1
2	Hi! We've assigned an officer to verify your land title in Karen. We'll update you after the Ardhi House search.	Dear Valued Customer, Your task VNH-L03IOJ (Verify Document) has been received. Risk level: High. A legal officer has been assigned. Warm regards, Vunoh Global Team	Vunoh: Document verification for Karen plot started. Ref: VNH-L03IOJ.	2026-04-18 22:19:40.285348+03	2
3	Jambo! We are matching you with a cleaner in Westlands for Friday. Access details confirmed?	Dear Valued Customer, Your task VNH-XW00HJ (Hire Service) has been received. Risk level: Low. Matching with providers now. Warm regards, Vunoh Global Team	Vunoh: Hiring cleaner for Westlands. Task VNH-XW00HJ in progress.	2026-04-18 22:19:40.295814+03	3
4	Safe flight! Your driver Moses (KDL 123X) will meet you at JKIA Saturday 6am. He's at the arrivals gate.	Dear Valued Customer, Your task VNH-3WMWWV (Airport Transfer) is COMPLETED. Your driver arrived on time. Warm regards, Vunoh Global Team	Vunoh: Airport pickup at JKIA finished. Welcome to Nairobi!	2026-04-18 22:19:40.306575+03	4
5	Hi, just checked your medical bill task. It's currently being reviewed by the local clinic.	Dear Valued Customer, Your task VNH-B3Z236 (Check Status) is in progress. We are fetching your records. Warm regards, Vunoh Global Team	Vunoh: Checking status of your previous task VNH-B3Z236.	2026-04-18 22:19:40.315843+03	5
6	Hi! Your task VNH-LHNOP8 has been received. We will be in touch shortly.	Dear Valued Customer, Your task VNH-LHNOP8 has been received. Warm regards, Vunoh Global Team	Vunoh: Task VNH-LHNOP8 received. We will contact you shortly.	2026-04-18 22:32:41.473884+03	6
7	Hi! Your task VNH-6UYWPG has been received. We will be in touch shortly.	Dear Valued Customer, Your task VNH-6UYWPG has been received. Warm regards, Vunoh Global Team	Vunoh: Task VNH-6UYWPG received. We will contact you shortly.	2026-04-18 22:34:39.95242+03	7
8	Hi! Your task VNH-ED63IF has been received. We will be in touch shortly.	Dear Valued Customer, Your task VNH-ED63IF has been received. Warm regards, Vunoh Global Team	Vunoh: Task VNH-ED63IF received. We will contact you shortly.	2026-04-18 22:35:21.861519+03	8
9	Hi! Your task VNH-5YOUQ0 has been received. We will be in touch shortly.	Dear Valued Customer, Your task VNH-5YOUQ0 has been received. Warm regards, Vunoh Global Team	Vunoh: Task VNH-5YOUQ0 received. We will contact you shortly.	2026-04-18 22:41:35.952748+03	9
10	Hello! We have initiated your urgent transfer of KES 25,000 to John Kamau. Next steps: verifying receipt.	Dear Valued Customer, Your task VNH-XLYWCA (Send Money) has been received. Risk level: Medium. We are currently processing the disbursement. Warm regards, Vunoh Global Team	Vunoh: Task VNH-XLYWCA started. KES 25k being sent to John Kamau.	2026-04-18 23:12:16.988704+03	10
11	Hi! We've assigned an officer to verify your land title in Karen. We'll update you after the Ardhi House search.	Dear Valued Customer, Your task VNH-4F8C15 (Verify Document) has been received. Risk level: High. A legal officer has been assigned. Warm regards, Vunoh Global Team	Vunoh: Document verification for Karen plot started. Ref: VNH-4F8C15.	2026-04-18 23:12:16.994208+03	11
12	Jambo! We are matching you with a cleaner in Westlands for Friday. Access details confirmed?	Dear Valued Customer, Your task VNH-7NH3ZC (Hire Service) has been received. Risk level: Low. Matching with providers now. Warm regards, Vunoh Global Team	Vunoh: Hiring cleaner for Westlands. Task VNH-7NH3ZC in progress.	2026-04-18 23:12:16.999171+03	12
13	Safe flight! Your driver Moses (KDL 123X) will meet you at JKIA Saturday 6am. He's at the arrivals gate.	Dear Valued Customer, Your task VNH-OSAU1L (Airport Transfer) is COMPLETED. Your driver arrived on time. Warm regards, Vunoh Global Team	Vunoh: Airport pickup at JKIA finished. Welcome to Nairobi!	2026-04-18 23:12:17.004311+03	13
14	Hi, just checked your medical bill task. It's currently being reviewed by the local clinic.	Dear Valued Customer, Your task VNH-KF8NH0 (Check Status) is in progress. We are fetching your records. Warm regards, Vunoh Global Team	Vunoh: Checking status of your previous task VNH-KF8NH0.	2026-04-18 23:12:17.009072+03	14
\.


--
-- Data for Name: assistant_taskstep; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.assistant_taskstep (id, step_number, description, task_id) FROM stdin;
1	1	Verify John Kamau's M-Pesa account status	1
2	2	Confirm KES 25,000 funds availability in primary account	1
3	3	Execute secure international transfer via authorized channel	1
4	4	Initiate M-Pesa disbursement to recipient in Nairobi	1
5	5	Send digital transaction receipt to customer	1
6	1	Collect parcel number and title deed copy from customer	2
7	2	Assign request to registered land surveyor in Nairobi	2
8	3	Conduct official search at Ministry of Lands (Ardhi House)	2
9	4	Verify boundaries and ownership history in Karen registry	2
10	5	Generate comprehensive verification report	2
11	1	Filter verified cleaning providers in Westlands area	3
12	2	Confirm availability for the requested Friday slot	3
13	3	Provide service quote and equipment requirements to customer	3
14	4	Schedule professional cleaner and confirm access details	3
15	5	Follow up for service quality feedback	3
16	1	Confirm arrival flight number and estimated time	4
17	2	Assign a verified driver with large vehicle for luggage	4
18	3	Share driver identity and plate number with customer	4
19	4	Monitor flight status for early arrival or delays	4
20	5	Pickup completed at JKIA arrivals terminal	4
21	1	Retrieve database record for previous medical task	5
22	2	Contact processing agent for latest status update	5
23	3	Generate status summary for the diaspora customer	5
24	4	Update customer via WhatsApp and dashboard	5
25	1	Task received	6
26	2	Being reviewed by our team	6
27	3	Customer will be notified	6
28	1	Task received	7
29	2	Being reviewed by our team	7
30	3	Customer will be notified	7
31	1	Task received	8
32	2	Being reviewed by our team	8
33	3	Customer will be notified	8
34	1	Task received	9
35	2	Being reviewed by our team	9
36	3	Customer will be notified	9
37	1	Verify John Kamau's M-Pesa account status	10
38	2	Confirm KES 25,000 funds availability in primary account	10
39	3	Execute secure international transfer via authorized channel	10
40	4	Initiate M-Pesa disbursement to recipient in Nairobi	10
41	5	Send digital transaction receipt to customer	10
42	1	Collect parcel number and title deed copy from customer	11
43	2	Assign request to registered land surveyor in Nairobi	11
44	3	Conduct official search at Ministry of Lands (Ardhi House)	11
45	4	Verify boundaries and ownership history in Karen registry	11
46	5	Generate comprehensive verification report	11
47	1	Filter verified cleaning providers in Westlands area	12
48	2	Confirm availability for the requested Friday slot	12
49	3	Provide service quote and equipment requirements to customer	12
50	4	Schedule professional cleaner and confirm access details	12
51	5	Follow up for service quality feedback	12
52	1	Confirm arrival flight number and estimated time	13
53	2	Assign a verified driver with large vehicle for luggage	13
54	3	Share driver identity and plate number with customer	13
55	4	Monitor flight status for early arrival or delays	13
56	5	Pickup completed at JKIA arrivals terminal	13
57	1	Retrieve database record for previous medical task	14
58	2	Contact processing agent for latest status update	14
59	3	Generate status summary for the diaspora customer	14
60	4	Update customer via WhatsApp and dashboard	14
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add task	7	add_task
26	Can change task	7	change_task
27	Can delete task	7	delete_task
28	Can view task	7	view_task
29	Can add task step	8	add_taskstep
30	Can change task step	8	change_taskstep
31	Can delete task step	8	delete_taskstep
32	Can view task step	8	view_taskstep
33	Can add task message	9	add_taskmessage
34	Can change task message	9	change_taskmessage
35	Can delete task message	9	delete_taskmessage
36	Can view task message	9	view_taskmessage
37	Can add status history	10	add_statushistory
38	Can change status history	10	change_statushistory
39	Can delete status history	10	delete_statushistory
40	Can view status history	10	view_statushistory
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	assistant	task
8	assistant	taskstep
9	assistant	taskmessage
10	assistant	statushistory
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-17 22:44:03.467668+03
2	auth	0001_initial	2026-04-17 22:44:03.723368+03
3	admin	0001_initial	2026-04-17 22:44:03.785132+03
4	admin	0002_logentry_remove_auto_add	2026-04-17 22:44:03.796976+03
5	admin	0003_logentry_add_action_flag_choices	2026-04-17 22:44:03.810431+03
6	assistant	0001_initial	2026-04-17 22:44:03.962178+03
7	contenttypes	0002_remove_content_type_name	2026-04-17 22:44:03.998639+03
8	auth	0002_alter_permission_name_max_length	2026-04-17 22:44:04.011921+03
9	auth	0003_alter_user_email_max_length	2026-04-17 22:44:04.028498+03
10	auth	0004_alter_user_username_opts	2026-04-17 22:44:04.044342+03
11	auth	0005_alter_user_last_login_null	2026-04-17 22:44:04.057369+03
12	auth	0006_require_contenttypes_0002	2026-04-17 22:44:04.064738+03
13	auth	0007_alter_validators_add_error_messages	2026-04-17 22:44:04.07702+03
14	auth	0008_alter_user_username_max_length	2026-04-17 22:44:04.103066+03
15	auth	0009_alter_user_last_name_max_length	2026-04-17 22:44:04.119462+03
16	auth	0010_alter_group_name_max_length	2026-04-17 22:44:04.138325+03
17	auth	0011_update_proxy_permissions	2026-04-17 22:44:04.156794+03
18	auth	0012_alter_user_first_name_max_length	2026-04-17 22:44:04.174765+03
19	sessions	0001_initial	2026-04-17 22:44:04.224262+03
20	assistant	0002_task_customer_email_task_customer_name_and_more	2026-04-18 22:52:29.456321+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: ivymalika
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Name: assistant_statushistory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.assistant_statushistory_id_seq', 1, false);


--
-- Name: assistant_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.assistant_task_id_seq', 14, true);


--
-- Name: assistant_taskmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.assistant_taskmessage_id_seq', 14, true);


--
-- Name: assistant_taskstep_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.assistant_taskstep_id_seq', 60, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ivymalika
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: assistant_statushistory assistant_statushistory_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.assistant_statushistory
    ADD CONSTRAINT assistant_statushistory_pkey PRIMARY KEY (id);


--
-- Name: assistant_task assistant_task_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.assistant_task
    ADD CONSTRAINT assistant_task_pkey PRIMARY KEY (id);


--
-- Name: assistant_task assistant_task_task_code_key; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.assistant_task
    ADD CONSTRAINT assistant_task_task_code_key UNIQUE (task_code);


--
-- Name: assistant_taskmessage assistant_taskmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.assistant_taskmessage
    ADD CONSTRAINT assistant_taskmessage_pkey PRIMARY KEY (id);


--
-- Name: assistant_taskstep assistant_taskstep_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.assistant_taskstep
    ADD CONSTRAINT assistant_taskstep_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: assistant_statushistory_task_id_e3ada214; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX assistant_statushistory_task_id_e3ada214 ON public.assistant_statushistory USING btree (task_id);


--
-- Name: assistant_task_task_code_de8d56cd_like; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX assistant_task_task_code_de8d56cd_like ON public.assistant_task USING btree (task_code varchar_pattern_ops);


--
-- Name: assistant_taskmessage_task_id_66aa3ef5; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX assistant_taskmessage_task_id_66aa3ef5 ON public.assistant_taskmessage USING btree (task_id);


--
-- Name: assistant_taskstep_task_id_e0185197; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX assistant_taskstep_task_id_e0185197 ON public.assistant_taskstep USING btree (task_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: ivymalika
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: assistant_statushistory assistant_statushistory_task_id_e3ada214_fk_assistant_task_id; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.assistant_statushistory
    ADD CONSTRAINT assistant_statushistory_task_id_e3ada214_fk_assistant_task_id FOREIGN KEY (task_id) REFERENCES public.assistant_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: assistant_taskmessage assistant_taskmessage_task_id_66aa3ef5_fk_assistant_task_id; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.assistant_taskmessage
    ADD CONSTRAINT assistant_taskmessage_task_id_66aa3ef5_fk_assistant_task_id FOREIGN KEY (task_id) REFERENCES public.assistant_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: assistant_taskstep assistant_taskstep_task_id_e0185197_fk_assistant_task_id; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.assistant_taskstep
    ADD CONSTRAINT assistant_taskstep_task_id_e0185197_fk_assistant_task_id FOREIGN KEY (task_id) REFERENCES public.assistant_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ivymalika
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 2QTQ9hWSQJdw9kHbyxA5E5vxbsTBnWQUOAOZEHZRHisuvGId0hnEhbVccj12NTH

